package sss.ui.milford.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Image;
import com.vaadin.ui.TextArea;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Structure extends VerticalLayout {
    protected HorizontalLayout topBar;
    protected CssLayout logoContainer;
    protected Button openstarLogo;
    protected HorizontalLayout toolsBar;
    protected CssLayout searchGroup;
    protected TextField searchField;
    protected Button searchBtn;
    protected Button notifyBell;
    protected CssLayout profilePicWrap;
    protected Image myProfilePic;
    protected Button profileName;
    protected CssLayout myStatus;
    protected Button balanceValuBtnLbl;
    protected HorizontalLayout allBelowTopBar;
    protected VerticalLayout lhs;
    protected CssLayout menuItems;
    protected Button statusButton;
    protected Button writeButton;
    protected Button newGrp;
    protected Button archiveButton;
    protected Button sentButton;
    protected Button junkButton;
    protected Button settingsButton;
    protected Button logoutButton;
    protected VerticalLayout content;
    protected Panel quickPostPanel;
    protected VerticalLayout quickPost;
    protected TextArea quickPostText;
    protected Button attachFile;
    protected Button attachPhoto;
    protected Button sendQuickPost;
    protected HorizontalLayout statusLayout;
    protected CssLayout navBtns;
    protected Button prevButton;
    protected Button nextButton;
    protected Panel itemPanel;
    protected VerticalLayout itemPanelVerticalLayout;
    protected VerticalLayout rhs;

    public Structure() {
        Design.read(this);
    }
}
