package sss.ui.milford.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button;
import com.vaadin.ui.RichTextArea;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Write extends VerticalLayout {
    protected ComboBox<String> messageSelect;
    protected ComboBox toCombo;
    protected TextField amountField;
    protected ComboBox scheduleCombo;
    protected RichTextArea writeDoco;
    protected Button sendButton;

    public Write() {
        Design.read(this);
    }
}
